default :
  Input :    
    Discovery dataset name : "Lymphoma_NLPHL"
    Expression matrix : "datasets/discovery/Lymphoma_NLPHL/LP_discovery_data.txt"
    #Possible values: "RNA-seq", "Affymetrix", "Other"
    Expression type : "RNA-seq"
    #Possible values: "Carcinoma_Fractions", "Lymphoma_Fractions" or a path to a file containing the precomputed cell fractions
    Cell type fractions : "LP_fractionsfile_disovery.txt" 
    Annotation file : "datasets/discovery/Lymphoma_NLPHL/LP_discovery_data.txt/LP_discovery_annotation.txt"
    Annotation file column to scale by : NULL
    Annotation file column(s) to plot : ["Pattern", "Status"]
    CIBERSORTx username : ""
    CIBERSORTx token : ""
    
  Output :
    Output folder : "Lymphoma_NLPHL"
  
  Pipeline settings :
    #Pipeline steps:
    #   step 1 (cell type fraction estimation)
    #   step 2 (cell type expression purification)
    #   step 3 (cell state discovery)
    #   step 4 (choosing the number of cell states)
    #   step 5 (extracting cell state information)
    #   step 6 (cell state QC filter)
    #   step 7 (advanced cell state QC filter)
    #   step 8 (ecotype discovery)
    Pipeline steps to skip : [7,] # Step 7 is skipped by default
    Number of threads : 10    
    Number of NMF restarts : 5
    Maximum number of states per cell type : 20
    Cophenetic coefficient cutoff : 0.95
    CIBERSORTx fractions Singularity path : NULL
    CIBERSORTx hires Singularity path : NULL
    Minimum number of states in ecotypes : 4
